Rerun bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1071,6 +1071,8 @@ Optional Packages:
   --with-netgroup         Build netgroup module for netgroups support
   --with-readline         compile with readline support
   --with-dmalloc          compile using Gray Watson's dmalloc
+  --with-rcmd-rank-list   Specify priority ordered list of rcmd modules.
+                          Default is mrsh,rsh,ssh,krb4,qsh,mqsh,exec,xcpu
 
 Some influential environment variables:
   CC          C compiler command
@@ -4084,7 +4086,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4087 "configure"' > conftest.$ac_ext
+  echo '#line 4089 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5683,7 +5685,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5686:" \
+echo "$as_me:5688:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6750,11 +6752,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6753: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6755: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6757: \$? = $ac_status" >&5
+   echo "$as_me:6759: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7018,11 +7020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7021: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7025: \$? = $ac_status" >&5
+   echo "$as_me:7027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7122,11 +7124,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7125: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7129: \$? = $ac_status" >&5
+   echo "$as_me:7131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9489,7 +9491,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9492 "configure"
+#line 9494 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9589,7 +9591,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9592 "configure"
+#line 9594 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11933,11 +11935,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11936: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11938: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11940: \$? = $ac_status" >&5
+   echo "$as_me:11942: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12037,11 +12039,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12040: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12042: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12044: \$? = $ac_status" >&5
+   echo "$as_me:12046: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13625,11 +13627,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13628: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13630: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13632: \$? = $ac_status" >&5
+   echo "$as_me:13634: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13729,11 +13731,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13732: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13734: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13736: \$? = $ac_status" >&5
+   echo "$as_me:13738: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15958,11 +15960,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15961: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15963: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15965: \$? = $ac_status" >&5
+   echo "$as_me:15967: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16226,11 +16228,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16229: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16231: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16233: \$? = $ac_status" >&5
+   echo "$as_me:16235: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16330,11 +16332,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16333: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16335: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16337: \$? = $ac_status" >&5
+   echo "$as_me:16339: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20340,7 +20342,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 20343 "configure"
+#line 20345 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21871,6 +21873,7 @@ else
   WITH_GNU_LD_TRUE='#'
   WITH_GNU_LD_FALSE=
 fi
+
 
 
 #
@@ -26691,6 +26694,45 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
   fi
+
+
+#
+#  Check for alternat rcmd rank list:
+#
+
+
+# Check whether --with-rcmd-rank-list or --without-rcmd-rank-list was given.
+if test "${with_rcmd_rank_list+set}" = set; then
+  withval="$with_rcmd_rank_list"
+   for t in `echo $withval | tr "," " "`; do
+			       if echo mrsh,rsh,ssh,krb4,qsh,mqsh,exec,xcpu | grep -q $t; then
+				     if test -z "$ac_cv_rcmd_rank_list" ; then
+					    ac_cv_rcmd_rank_list=\"$t\"
+				      else
+				        ac_cv_rcmd_rank_list="$ac_cv_rcmd_rank_list, \"$t\""
+				      fi
+				   else
+				     { { echo "$as_me:$LINENO: error: Invalid rcmd type $t!" >&5
+echo "$as_me: error: Invalid rcmd type $t!" >&2;}
+   { (exit 1); exit 1; }; }
+				   fi
+			   done
+
+fi;
+
+		echo "$as_me:$LINENO: checking rcmd rank list" >&5
+echo $ECHO_N "checking rcmd rank list... $ECHO_C" >&6
+		if test -z "$ac_cv_rcmd_rank_list"; then
+		   ac_cv_rcmd_rank_list='"mrsh", "rsh", "ssh", "krb4", "qsh", "mqsh", "exec", "xcpu"'
+        fi
+        echo "$as_me:$LINENO: result: $ac_cv_rcmd_rank_list" >&5
+echo "${ECHO_T}$ac_cv_rcmd_rank_list" >&6
+
+
+cat >>confdefs.h <<_ACEOF
+#define RCMD_RANK_LIST $ac_cv_rcmd_rank_list
+_ACEOF
+
 
 
 if test "$ac_static_modules" = "yes" ; then
